# Generated by Django 4.2.3 on 2023-07-13 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_faq_remove_advice_name_remove_review_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='teacherOrCourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nam', to='api.teacher', verbose_name='Преподаватель или курс'),
        ),
    ]
